Update package specs
[#155479602]

Signed-off-by: Peter Stone <pstone@pivotal.io>

diff --git a/scripts/sync-package-specs b/scripts/sync-package-specs
--- a/scripts/sync-package-specs
+++ b/scripts/sync-package-specs
@@ -1,37 +1,37 @@
-# Copyright (C) 2015-Present Pivotal Software, Inc. All rights reserved.
-# This program and the accompanying materials are made available under the terms of the under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-# http://www.apache.org/licenses/LICENSE-2.0
-# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
-
 #!/bin/bash -e
 
+go get github.com/vito/gosub
+
+if [ ! $(which gosub) ]; then
+  echo "Gosub required to update dependencies in bosh/*/spec files."
+  echo 'Please install with `go get github.com/vito/gosub`'
+  exit 1
+fi
+
 pushd $(dirname $0)/..
+  function sync_package() {
+    bosh_pkg=${1}
+    shift
 
-function sync_package() {
-  bosh_pkg=${1}
-  shift
+    (
+      set -e
 
-  (
-    set -e
+      cd packages/${bosh_pkg}
 
-    cd packages/${bosh_pkg}
+      {
+        cat spec | grep -v '# gosub'
 
-    {
-      cat spec | grep -v '# gosub'
+        for package in $(gosub list "$@"); do
+          repo=$(echo ${2} | cut -f1-3 -d/)
+          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
+        done
+      } > spec.new
 
-      for package in $(gosub list "$@"); do
-        repo=$(echo ${2} | cut -f1-3 -d/)
-        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
-      done
-    } > spec.new
+      mv spec.new spec
+    )
+  }
 
-    mv spec.new spec
-  )
-}
+  sync_package service-metrics -app github.com/cloudfoundry/service-metrics
 
-sync_package service-metrics -app github.com/cloudfoundry/service-metrics
-
-wait
-
+  wait
 popd
